### PR TITLE
update build

### PR DESCRIPTION
**Pull request by Szeraax**
This PR makes the app build and deploy for Wear OS. I suspect that it has to do with the fact new Wear OS is 64-bit only. When I launch the app, I get the warning that this app was made for an older version of Wear OS and may be incompatible, but the app runs perfectly fine.

Biggest hangup was the gradle dir change to `<option name="gradleHome" value="$USER_HOME$/.gradle/installs/gradle-8.5" />`

### CODE REVIEW

**Comment by Szeraax** [comment]
Look, I don't know what I'm doing. I installed Android Studio today and did a deploy from VCS to get the project in. From there, I used the upgrade helper to get deps updated. 

I don't know what it would take to fix the warning about old versions. Maybe I just need to update targetSdkVersion 21 to 33. I'll test that next and probably add it to this PR. 

If you don't care about this awesome game anymore or don't like how I've done things, please feel free to ignore this or make your own edits. It does fix #1 though for me, so I'm happy that I can play this game on my brand new watch.

**Comment by Szeraax** [comment]
There is a warning about updating the sdk version manually, but everything in the app still works great, so I dunno. 

And removed the buildconfig as it seems to affect nothing and is deprecated.

**Comment by Szeraax** [comment]
I'm honestly surprised at how easy it was to get this going. Props to Google for this working so easily for dummies like me.

**Comment by errcw** [comment]
This is great, thank you for pushing through the toil to get this working!

**Pull request merged**
